#### FDC ####
gamma_falloff: 0.0
gamma: 1.
epsilon: 0.005
num_md_iterations: 3 # number of outer (mirror descent) steps
beta: 0.9
adjoint_matching:
  num_iterations: 10 # how often the adjoint matching is run after the bandit step (if use_bandit is set to false this is the only optimization step)
  batch_size: 128 # batch_size is both used for number samples - sampled per batch an then for updates
  clip_grad_norm: 0.4 # float - if 0.0 no clipping is done
  clip_loss: 1e5 # float - if 0.0 no clipping is done
  lr: 0.01
  finetune_steps: 10
  sampling:
    num_samples: 40
    num_integration_steps: 40
